### ISSUE TITLE
Better syntax highlightings for jade and sass?

### ISSUE THREAD

**Issue by NemoAlex** [BrainBuzzer/vuejs-sublime-complete#1]
Thanks for such a useful package.
Now I'm using [Jade.tmLanguage](https://github.com/miksago/jade-tmbundle/blob/master/Syntaxes/Jade.tmLanguage) for .jade files' highlighting. It's much more better than the one built in there.
So I'm gonna ask: is that possible to just call user's default language settings in .vue files?
Same question on sass highlighting.

**Comment by Gomah** [comment]
:+1: // https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.tmLanguage

**Comment by BrainBuzzer** [comment]
@Gomah got that right.
