### ISSUE TITLE
My syntax is changing to Vue Component when I first paste in php code

### ISSUE THREAD

**Issue by jakeparis** [BrainBuzzer/vuejs-sublime-complete#15]
When I open a new file, and paste in `<?php` at the top of the file (with or without code after it), the syntax is automatically changing to Vue Component. 

If I manually type`<?php` that doesn't happen. 

This plugin shouldn't switch syntax to Vue upon seeing `<?php`

**Comment by dmyers** [comment]
Might be useful to check out the [official Vue.js Sublime package](https://github.com/vuejs/vue-syntax-highlight). I'm not sure what the main difference between them is other than the completions, but for syntax highlighting I think they are similar in functionality and I also had this same problem and just decided to remove this package to see if it fixes it.

**Comment by BrainBuzzer** [comment]
I have not been updating this package for past 2 years. It is advisable to get the official Vue package for sublime. I have switched the editor to Visual Studio Code and I'm pretty happy with the tooling support in VS Code. I suggest you to look into that too.
